# Generated by Django 4.1 on 2022-09-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='video_file',
        ),
    ]
